name: Python Cron Job with Dependencies

on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Lấy mã nguồn từ repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Chọn phiên bản Python (3.8, 3.9, 3.10,...)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Cài đặt các thư viện từ requirements.txt

      - name: Run Python script
        run: python script.py  # Thay script.py bằng tên file script của bạn
